### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by Scottmacaz** [TonyCurtisLives/VirtualDog#2]
Hi Tony,

I went through the setup, but when I start the server I get the following error.  Any ideas?

C:\TestCode\ps\VirtualDog>npm start

> VitrualDog@0.0.1 start C:\TestCode\ps\VirtualDog
> concurrently "http-server -a 0.0.0.0 -p 8042" "node server/tinyserv" "tsc -w"

[1] module.js:327
[1]     throw err;
[1]     ^
[1]
[1] Error: Cannot find module 'C:\TestCode\ps\VirtualDog\server\tinyserv'
[1]     at Function.Module._resolveFilename (module.js:325:15)
[1]     at Function.Module._load (module.js:276:25)
[1]     at Function.Module.runMain (module.js:441:10)
[1]     at startup (node.js:139:18)
[1]     at node.js:974:3
[1] node server/tinyserv exited with code 1
[2] module.js:327
[2]     throw err;
[2]     ^

**Comment by TonyCurtisLives** [comment]
The issue was that TypeScript needed to be compiled prior to npm start. Now npm install compiles TypeScript. The new code is in the begin branch, and will shortly be added to the end branch.

**Comment by TonyCurtisLives** [comment]
I updated the setup in the begin branch. Try it again, though it would have
worked if you ran it again. The TypeScript needs to compile, so now that
you have run it, it has compiled, just after the error. Sorry for the late
response, I actually fixed this a few days ago.
