### ISSUE TITLE
Unable to start in browser

### ISSUE THREAD

**Issue by arisliang** [TonyCurtisLives/VirtualDog#4]
I followed project setup steps:
npm install
npm start

The server serves up to the port, once opening the page in chrome, it got loads of error in console as below. What could be the issue?

-------------------
localhost/:35 GET http://localhost:8042/app/animals/otherAnimal.Module.js 
localhost/:17 GET http://localhost:8042/app/dogs/idog.js 
localhost/:17 GET http://localhost:8042/app/dogs/idog.js 
config.ts:24 Uncaught TypeError: Cannot read property 'elevated' of undefined
    at dogsrus.virtdog.dogsrus.virtdog (config.ts:24)
    at dogsrus (config.ts:73)
    at config.ts:73
dogsrus.virtdog.dogsrus.virtdog @ config.ts:24
dogsrus @ config.ts:73
(anonymous) @ config.ts:73
localhost/:35 GET http://localhost:8042/app/animals/otherAnimal.Module.js 
otherAnimalController.ts:40Uncaught TypeError: virtdog.getModuleOtherAnimal is not a function
    at dogsrus.virtdog.dogsrus.virtdog (otherAnimalController.ts:40)
    at dogsrus (otherAnimalController.ts:41)
    at otherAnimalController.ts:41
dogsrus.virtdog.dogsrus.virtdog @ otherAnimalController.ts:40
dogsrus @ otherAnimalController.ts:41
(anonymous) @ otherAnimalController.ts:41
angular.js:63 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module app.otherAnimal due to:
Error: [$injector:nomod] Module 'app.otherAnimal' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.20/$injector/nomod?p0=app.otherAnimal
    at http://localhost:8042/bower_components/angular/angular.js:63:12
    at http://localhost:8042/bower_components/angular/angular.js:1778:17
    at ensure (http://localhost:8042/bower_components/angular/angular.js:1702:38)
    at module (http://localhost:8042/bower_components/angular/angular.js:1776:14)
    at http://localhost:8042/bower_components/angular/angular.js:4131:22
    at forEach (http://localhost:8042/bower_components/angular/angular.js:326:20)
    at loadModules (http://localhost:8042/bower_components/angular/angular.js:4115:5)
    at http://localhost:8042/bower_components/angular/angular.js:4132:40
    at forEach (http://localhost:8042/bower_components/angular/angular.js:326:20)
    at loadModules (http://localhost:8042/bower_components/angular/angular.js:4115:5)
http://errors.angularjs.org/1.3.20/$injector/modulerr?p0=app.otherAnimal&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'app.otherAnimal'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.20%2F%24injector%2Fnomod%3Fp0%3Dapp.otherAnimal%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A63%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1778%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1702%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1776%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4131%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4115%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4132%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4115%3A5)
    at http://localhost:8042/bower_components/angular/angular.js:63:12
    at http://localhost:8042/bower_components/angular/angular.js:4154:15
    at forEach (http://localhost:8042/bower_components/angular/angular.js:326:20)
    at loadModules (http://localhost:8042/bower_components/angular/angular.js:4115:5)
    at http://localhost:8042/bower_components/angular/angular.js:4132:40
    at forEach (http://localhost:8042/bower_components/angular/angular.js:326:20)
    at loadModules (http://localhost:8042/bower_components/angular/angular.js:4115:5)
    at createInjector (http://localhost:8042/bower_components/angular/angular.js:4041:11)
    at doBootstrap (http://localhost:8042/bower_components/angular/angular.js:1455:20)
    at bootstrap (http://localhost:8042/bower_components/angular/angular.js:1476:12)
http://errors.angularjs.org/1.3.20/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20app.otherAnimal%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'app.otherAnimal'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.20%2F%24injector%2Fnomod%3Fp0%3Dapp.otherAnimal%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A63%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1778%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1702%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1776%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4131%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4115%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4132%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4115%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.20%2F%24injector%2Fmodulerr%3Fp0%3Dapp.otherAnimal%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'app.otherAnimal'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.3.20%252F%2524injector%252Fnomod%253Fp0%253Dapp.otherAnimal%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A63%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A1778%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A1702%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A1776%253A14)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A4131%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A326%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A4115%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A4132%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A326%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A4115%253A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A63%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4154%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4115%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4132%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4115%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4041%3A11)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1455%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1476%3A12)
    at http://localhost:8042/bower_components/angular/angular.js:63:12
    at http://localhost:8042/bower_components/angular/angular.js:1778:17
    at ensure (http://localhost:8042/bower_components/angular/angular.js:1702:38)
    at module (http://localhost:8042/bower_components/angular/angular.js:1776:14)
    at http://localhost:8042/bower_components/angular/angular.js:4131:22
    at forEach (http://localhost:8042/bower_components/angular/angular.js:326:20)
    at loadModules (http://localhost:8042/bower_components/angular/angular.js:4115:5)
    at http://localhost:8042/bower_components/angular/angular.js:4132:40
    at forEach (http://localhost:8042/bower_components/angular/angular.js:326:20)
    at loadModules (http://localhost:8042/bower_components/angular/angular.js:4115:5)
http://errors.angularjs.org/1.3.20/$injector/modulerr?p0=app.otherAnimal&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'app.otherAnimal'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.20%2F%24injector%2Fnomod%3Fp0%3Dapp.otherAnimal%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A63%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1778%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1702%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1776%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4131%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4115%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4132%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4115%3A5)
    at http://localhost:8042/bower_components/angular/angular.js:63:12
    at http://localhost:8042/bower_components/angular/angular.js:4154:15
    at forEach (http://localhost:8042/bower_components/angular/angular.js:326:20)
    at loadModules (http://localhost:8042/bower_components/angular/angular.js:4115:5)
    at http://localhost:8042/bower_components/angular/angular.js:4132:40
    at forEach (http://localhost:8042/bower_components/angular/angular.js:326:20)
    at loadModules (http://localhost:8042/bower_components/angular/angular.js:4115:5)
    at createInjector (http://localhost:8042/bower_components/angular/angular.js:4041:11)
    at doBootstrap (http://localhost:8042/bower_components/angular/angular.js:1455:20)
    at bootstrap (http://localhost:8042/bower_components/angular/angular.js:1476:12)
http://errors.angularjs.org/1.3.20/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20app.otherAnimal%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'app.otherAnimal'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.20%2F%24injector%2Fnomod%3Fp0%3Dapp.otherAnimal%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A63%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1778%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1702%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1776%3A14)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4131%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4115%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4132%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4115%3A5)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.20%2F%24injector%2Fmodulerr%3Fp0%3Dapp.otherAnimal%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'app.otherAnimal'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.3.20%252F%2524injector%252Fnomod%253Fp0%253Dapp.otherAnimal%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A63%253A12%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A1778%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A1702%253A38)%250A%2520%2520%2520%2520at%2520module%2520(http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A1776%253A14)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A4131%253A22%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A326%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A4115%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A4132%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A326%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%253A8042%252Fbower_components%252Fangular%252Fangular.js%253A4115%253A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A63%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4154%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4115%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4132%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A326%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4115%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A4041%3A11)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1455%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2Flocalhost%3A8042%2Fbower_components%2Fangular%2Fangular.js%3A1476%3A12)
    at http://localhost:8042/bower_components/angular/angular.js:63:12
    at http://localhost:8042/bower_components/angular/angular.js:4154:15
    at forEach (http://localhost:8042/bower_components/angular/angular.js:326:20)
    at loadModules (http://localhost:8042/bower_components/angular/angular.js:4115:5)
    at createInjector (http://localhost:8042/bower_components/angular/angular.js:4041:11)
    at doBootstrap (http://localhost:8042/bower_components/angular/angular.js:1455:20)
    at bootstrap (http://localhost:8042/bower_components/angular/angular.js:1476:12)
    at angularInit (http://localhost:8042/bower_components/angular/angular.js:1370:5)
    at http://localhost:8042/bower_components/angular/angular.js:26446:5
    at HTMLDocument.trigger (http://localhost:8042/bower_components/angular/angular.js:2773:7)
(anonymous) @ angular.js:63
(anonymous) @ angular.js:4154
forEach @ angular.js:326
loadModules @ angular.js:4115
createInjector @ angular.js:4041
doBootstrap @ angular.js:1455
bootstrap @ angular.js:1476
angularInit @ angular.js:1370
(anonymous) @ angular.js:26446
trigger @ angular.js:2773
eventHandler @ angular.js:3047

**Comment by TonyCurtisLives** [comment]
I wonder what branch you pulled? s/b feature/begin (or feature/end if you want to see final product). That error would indicate that some of the code is out of date, so I really think this is an issue with the branch/commit point you are using.

**Comment by ReyPena** [comment]
I have the same problem and im using feature/begin, is this problem been solve ?

**Comment by deeprastogi** [comment]
same problem with feature/end.
